// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3VuUYqUx9fM3kqpL3bRmvVFA7fGYXmH4',
    appId: '1:335376641060:web:d60c53a517062230453cb1',
    messagingSenderId: '335376641060',
    projectId: 'blackpearlflutter',
    authDomain: 'blackpearlflutter.firebaseapp.com',
    storageBucket: 'blackpearlflutter.appspot.com',
    measurementId: 'G-96JQ49WVFZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXPqO-cfnskg5KaY2trXKjOZgDSyXVkXw',
    appId: '1:335376641060:android:7461e8c5f4584960453cb1',
    messagingSenderId: '335376641060',
    projectId: 'blackpearlflutter',
    storageBucket: 'blackpearlflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK5NcbDnkn5UqU0iDemaEk1Xy2L27oQ5I',
    appId: '1:335376641060:ios:0da23d0ed71f08e6453cb1',
    messagingSenderId: '335376641060',
    projectId: 'blackpearlflutter',
    storageBucket: 'blackpearlflutter.appspot.com',
    iosClientId: '335376641060-99mgrj9snfu2c456v3ser3vum6pll9c2.apps.googleusercontent.com',
    iosBundleId: 'com.example.blackpearl',
  );
}
